"""v1.1.0: aggregate benchmark runs into tables (mean +- 95% CI over seeds, paired delta vs BEB) and plots.
Usage (from this directory):
  ../../venv/bin/python aggregate_bench.py results/bench-<ts> [--out docs/figures/v1.1.0] [--stepTime 0.01] [--warmup 300]
Reads <benchDir>/manifest.csv (PASS rows only). Every mode uses the same per-step policy window (steps >= warmup).
Throughput = per-step rx * payload bits / step time, from trace.csv, identically for beb / global / independent.
Reward is NOT compared across modes: the trace reward is each mode's own per-AP env reward (not used here).
"""
import argparse
import csv
import os
from collections import defaultdict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

from summarize_run import summarize  # noqa: E402

# two-sided 95% Student t critical values, df = 1..10 (no scipy in the venv)
T95 = {1: 12.706, 2: 4.303, 3: 3.182, 4: 2.776, 5: 2.571, 6: 2.447, 7: 2.365, 8: 2.306, 9: 2.262, 10: 2.228}
MODES = ["beb", "global", "independent"]
LABEL = {"beb": "BEB (802.11)", "global": "Global-CW OSCAR", "independent": "Independent per-AP"}
COLOR = {"beb": "#888888", "global": "#d95f02", "independent": "#1b9e77"}

parser = argparse.ArgumentParser()
parser.add_argument("bench_dir")
parser.add_argument("--out", default="docs/figures/v1.1.0")
parser.add_argument("--stepTime", type=float, default=0.01)
parser.add_argument("--warmup", type=int, default=300)
args = parser.parse_args()


def ci(x):
    """(mean, half-width of the 95% CI). Half-width is nan for n < 2."""
    x = np.asarray(x, dtype=float)
    if len(x) < 2:
        return float(x.mean()), float("nan")
    assert len(x) - 1 in T95, "need n <= 11 seeds"
    return float(x.mean()), T95[len(x) - 1] * float(x.std(ddof=1)) / np.sqrt(len(x))


def fmt(x, d=2):
    m, h = ci(x)
    return "%.*f ± %.*f" % (d, m, d, h) if np.isfinite(h) else "%.*f (n=1)" % (d, m)


def convergence_step(tot, win=100, tol=0.05, tail=300):
    """First step after which the rolling-`win` mean of aggregate throughput stays within tol of the last-`tail` mean."""
    roll = np.convolve(tot, np.ones(win) / win, mode="valid")
    ref = tot[-tail:].mean()
    bad = np.where(np.abs(roll - ref) > tol * ref)[0]
    return int(bad[-1] + win) if len(bad) else 0


runs = defaultdict(lambda: defaultdict(dict))  # topo -> mode -> {seed: summary}
base = args.bench_dir
for r in csv.DictReader(open(os.path.join(base, "manifest.csv"))):
    if r["result"] != "PASS":
        continue
    s = summarize(r["run_dir"], args.stepTime, args.warmup)
    s["conv"] = convergence_step(s["tot"])
    runs[r["topo"]][r["mode"]][int(r["seed"])] = s

topos = list(runs)
os.makedirs(args.out, exist_ok=True)
md = ["# v1.1.0 benchmark tables (generated by aggregate_bench.py)", "",
      "Policy window = steps >= %d (%.2f s of stepping); mean ± 95%% CI (Student t) over seeds; throughput in Mbps." %
      (args.warmup, args.warmup * args.stepTime), ""]

for topo in topos:
    modes = [m for m in MODES if m in runs[topo]]
    n_aps = len(next(iter(runs[topo][modes[0]].values()))["aps"])
    md += ["## %s STAs per AP" % topo, "",
           "| Mode | n | Aggregate | " + " | ".join("AP%d" % (a + 1) for a in range(n_aps)) +
           " | Phy loss | Jain | " + " | ".join("CW AP%d last-100" % (a + 1) for a in range(n_aps)) + " | Convergence step |",
           "|---|---|---|" + "---|" * (n_aps * 2 + 3)]
    for m in modes:
        S = list(runs[topo][m].values())
        md.append("| %s | %d | %s | %s | %s | %s | %s | %s |" % (
            LABEL[m], len(S), fmt([s["tot_policy"] for s in S]),
            " | ".join(fmt([s["thr_policy"][a] for s in S]) for a in S[0]["aps"]),
            fmt([s["loss_policy"] for s in S], 3), fmt([s["jain_policy"] for s in S], 3),
            " | ".join(fmt([s["cw"][a][-100:].mean() for s in S], 0) for a in S[0]["aps"]),
            fmt([s["conv"] for s in S], 0)))
    md.append("")
    if "beb" in runs[topo]:
        md += ["Paired difference vs BEB (same ns-3 seed), aggregate throughput:", "",
               "| Mode | n pairs | Δ Mbps | Δ % |", "|---|---|---|---|"]
        for m in modes:
            if m == "beb":
                continue
            seeds = sorted(set(runs[topo][m]) & set(runs[topo]["beb"]))
            if not seeds:
                continue
            d = [runs[topo][m][s]["tot_policy"] - runs[topo]["beb"][s]["tot_policy"] for s in seeds]
            p = [100 * x / runs[topo]["beb"][s]["tot_policy"] for x, s in zip(d, seeds)]
            md.append("| %s | %d | %s | %s |" % (LABEL[m], len(seeds), fmt(d), fmt(p, 1)))
        md.append("")

with open(os.path.join(args.out, "tables.md"), "w") as f:
    f.write("\n".join(md) + "\n")
print("\n".join(md))

# --- plots ---------------------------------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 4))
w = 0.8 / len(MODES)
for j, m in enumerate(MODES):
    ms, hs, xs = [], [], []
    for i, t in enumerate(topos):
        if m in runs[t]:
            mean, h = ci([s["tot_policy"] for s in runs[t][m].values()])
            ms.append(mean); hs.append(0 if np.isnan(h) else h); xs.append(i + (j - 1) * w)
    ax.bar(xs, ms, w, yerr=hs, capsize=3, label=LABEL[m], color=COLOR[m])
ax.set_xticks(range(len(topos))); ax.set_xticklabels(topos)
ax.set_xlabel("STAs per AP"); ax.set_ylabel("Aggregate throughput, policy window (Mbps)")
ax.legend(); ax.set_title("Aggregate throughput (mean ± 95% CI over seeds)")
fig.tight_layout(); fig.savefig(os.path.join(args.out, "aggregate_throughput.png"), dpi=150); plt.close(fig)

fig, axes = plt.subplots(1, len(topos), figsize=(3.6 * len(topos), 3.8), squeeze=False)
for ax, t in zip(axes[0], topos):
    for j, m in enumerate(MODES):
        if m not in runs[t]:
            continue
        S = list(runs[t][m].values())
        bottom = 0
        for a in S[0]["aps"]:
            v = np.mean([s["thr_policy"][a] for s in S])
            ax.bar(j, v, bottom=bottom, color=COLOR[m], alpha=1.0 if a == 1 else 0.55, edgecolor="white")
            bottom += v
    ax.set_xticks(range(len(MODES))); ax.set_xticklabels(["BEB", "Global", "Indep."])
    ax.set_title(t + " (AP1 dark, AP2 light)"); ax.set_ylabel("Mbps")
fig.tight_layout(); fig.savefig(os.path.join(args.out, "per_ap_throughput.png"), dpi=150); plt.close(fig)

fig, axes = plt.subplots(len(topos), 1, figsize=(8, 2.8 * len(topos)), squeeze=False)
for ax, t in zip(axes[:, 0], topos):
    for m in MODES:
        if m not in runs[t]:
            continue
        roll = np.mean([np.convolve(s["tot"], np.ones(100) / 100, mode="valid") for s in runs[t][m].values()], axis=0)
        ax.plot(np.arange(len(roll)) + 100, roll, color=COLOR[m], label=LABEL[m])
    ax.axvline(args.warmup, color="k", lw=0.5, ls=":")
    ax.set_title("%s: rolling-100 aggregate throughput (mean over seeds)" % t); ax.set_ylabel("Mbps")
axes[-1, 0].set_xlabel("step"); axes[0, 0].legend(fontsize=8)
fig.tight_layout(); fig.savefig(os.path.join(args.out, "convergence.png"), dpi=150); plt.close(fig)

fig, axes = plt.subplots(len(topos), 2, figsize=(10, 2.8 * len(topos)), squeeze=False)
for row, t in zip(axes, topos):
    for ax, m in zip(row, ["global", "independent"]):
        if m not in runs[t]:
            continue
        S = list(runs[t][m].values())
        for a in S[0]["aps"]:
            cw = np.mean([np.convolve(s["cw"][a], np.ones(50) / 50, mode="valid") for s in S], axis=0)
            ax.plot(np.arange(len(cw)) + 50, cw, label="AP%d" % a)
        ax.set_title("%s, %s: CW (rolling-50, mean over seeds)" % (t, LABEL[m]), fontsize=9)
        ax.set_yscale("log", base=2); ax.legend(fontsize=7)
fig.tight_layout(); fig.savefig(os.path.join(args.out, "cw_traces.png"), dpi=150); plt.close(fig)
print("wrote tables + 4 figures to", args.out)
