#include "ns3/core-module.h"
#include "ns3/applications-module.h"
#include "ns3/wifi-module.h"
#include "ns3/mobility-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include "ns3/opengym-module.h"
//#include "ns3/csma-module.h"
#include "ns3/propagation-module.h"
#include "ns3/flow-monitor-helper.h"
#include "ns3/ipv4-flow-classifier.h"
#include "ns3/yans-wifi-channel.h"

#include <fstream>
#include <string>
#include <math.h>
#include <ctime>   //timestampi
#include <iomanip> // put_time
#include <deque>
#include <algorithm>
#include <csignal>
#include <sstream>
#include <vector>
#include <map>
#include "scenario.h"

using namespace std;
using namespace ns3;

NS_LOG_COMPONENT_DEFINE("OpenGym");

void installTrafficGenerator(Ptr<ns3::Node> fromNode, Ptr<ns3::Node> toNode, int port, string offeredLoad, double startTime);
void PopulateARPcache();
void recordHistory();
std::vector<uint32_t> parseApStaCounts(std::string apStaCounts, int nWifi);
void logTopology(NodeContainer wifiStaNode, NodeContainer wifiApNode, std::vector<NodeContainer> apStaNodes);

double envStepTime = 0.01;
double simulationTime = 10; //seconds
double current_time = 0.0;
bool verbose = false;
int end_delay = 0;
bool dry_run = false;
bool disable_gym = false;

Ptr<FlowMonitor> monitor;
FlowMonitorHelper flowmon;
ofstream outfile ("scratch/linear-mesh/CW_data.csv", fstream::out);

uint32_t CW = 0;

// v0.5.0 per-AP CW. Index = AP index. g_apBss[i] = AP i + its STAs; g_apCwMin/Max = last value written to that BSS.
std::vector<NodeContainer> g_apBss;
std::vector<uint32_t> g_apCwMin;
std::vector<uint32_t> g_apCwMax;
std::vector<uint32_t> g_apCwOverride; // --apCws (empty = every AP uses CW)
bool g_apCwOk = true;                 // cleared by any failing readback


uint32_t history_length = 20;
deque<float> history;

string type = "discrete";
bool non_zero_start = false;
Scenario *wifiScenario;


/*
Define observation space
*/
Ptr<OpenGymSpace> MyGetObservationSpace(void)
{
    float low = 0.0;
    float high = 10.0;
    std::vector<uint32_t> shape = {
        history_length,
    };
    std::string dtype = TypeNameGet<float>();
    Ptr<OpenGymBoxSpace> space = CreateObject<OpenGymBoxSpace>(low, high, shape, dtype);
    if (verbose)
        NS_LOG_UNCOND("MyGetObservationSpace: " << space);
    return space;
}

/*
Define action space
*/
Ptr<OpenGymSpace> MyGetActionSpace(void)
{
    float low = 0.0;
    float high = 10.0;
    std::vector<uint32_t> shape = {
        1,
    };
    std::string dtype = TypeNameGet<float>();
    Ptr<OpenGymBoxSpace> space = CreateObject<OpenGymBoxSpace>(low, high, shape, dtype);
    if (verbose)
        NS_LOG_UNCOND("MyGetActionSpace: " << space);
    return space;
}

/*
Define extra info. Optional
*/
uint64_t g_rxPktNum = 0;
uint64_t g_txPktNum = 0;

// v0.4.0 per-AP accounting (index = AP index). Sized in main(); the globals above stay the network totals.
std::vector<uint64_t> g_apRxPkt;     // packets received by the sinks hosted on AP i
std::vector<uint64_t> g_apPhyTxPkt;  // PhyTxBegin on AP i and its STAs (beacons/ACKs included, like g_txPktNum)
std::vector<uint64_t> g_apAppTxPkt;  // data packets generated by the OnOff apps of AP i's STAs
bool g_apCountersReset = false;      // set when the warm-up reset ran; sink GetReceived() is not reset

void resetApCounters(void)
{
    std::fill(g_apRxPkt.begin(), g_apRxPkt.end(), 0);
    std::fill(g_apPhyTxPkt.begin(), g_apPhyTxPkt.end(), 0);
    std::fill(g_apAppTxPkt.begin(), g_apAppTxPkt.end(), 0);
    g_apCountersReset = true;
}

double jain_index(void)
{
    double flowThr;
    Ptr<Ipv4FlowClassifier> classifier = DynamicCast<Ipv4FlowClassifier>(flowmon.GetClassifier());
    std::map<FlowId, FlowMonitor::FlowStats> stats = monitor->GetFlowStats();

    double nominator;
    double denominator;
    double n=0;
    double station_id = 0;
    for (std::map<FlowId, FlowMonitor::FlowStats>::const_iterator i = stats.begin(); i != stats.end(); ++i)
    {
        flowThr = i->second.rxBytes;
        flowThr /= wifiScenario->getStationUptime(station_id, current_time);
        if(flowThr>0){
            nominator += flowThr;
            denominator += flowThr*flowThr;
            n++;
        }
        station_id++;
    }
    nominator *= nominator;
    denominator *= n;
    return nominator/denominator;
}

std::string MyGetExtraInfo(void)
{
    static float ticks = 0.0;
    static float lastValue = 0.0;
    float obs = g_rxPktNum - lastValue;
    lastValue = g_rxPktNum;
    ticks += envStepTime;

    float sentMbytes = obs * (1500 - 20 - 8 - 8) * 8.0 / 1024 / 1024;

    std::string myInfo = std::to_string(sentMbytes);
    myInfo = myInfo + "|" + to_string(CW) + "|";
    myInfo = myInfo + to_string(wifiScenario->getActiveStationCount(ticks)) + "|";
    myInfo = myInfo + to_string(jain_index());

    if (verbose)
        NS_LOG_UNCOND("MyGetExtraInfo: " << myInfo);

    return myInfo;
}

std::string beTxopPath(uint32_t nodeId)
{
    return "/NodeList/" + std::to_string(nodeId) + "/DeviceList/*/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/BE_Txop/$ns3::QosTxop";
}

// Write the BE MinCw/MaxCw of AP `ap` and every STA of its BSS. Other BSSs are not touched.
void setApCw(uint32_t ap, uint32_t cwMin, uint32_t cwMax)
{
    const NodeContainer &bss = g_apBss.at(ap);
    for (uint32_t n = 0; n < bss.GetN(); ++n)
    {
        std::string path = beTxopPath(bss.Get(n)->GetId());
        Config::Set(path + "/MinCw", UintegerValue(cwMin));
        Config::Set(path + "/MaxCw", UintegerValue(cwMax));
    }
    g_apCwMin.at(ap) = cwMin;
    g_apCwMax.at(ap) = cwMax;
}

// STAs overwrite their BE CW from their AP's EDCA parameter set, which carries CW as 2^ECW-1
// (ECW = floor(log2(CW+1))), so a STA legitimately reads CW or that rounded-down value.
uint32_t edcaRoundedCw(uint32_t cw)
{
    uint32_t p = 1;
    while (p * 2 <= cw + 1)
        p *= 2;
    return p - 1;
}

// Read MinCw/MaxCw back from the nodes. The AP must match the value written exactly; STAs may
// match it exactly or after EDCA rounding. Clears g_apCwOk on any mismatch.
void checkApCw(std::string label)
{
    bool ok = true;
    NS_LOG_UNCOND("CW readback [" << label << "] t=" << Simulator::Now().GetSeconds() << " s:");
    for (uint32_t ap = 0; ap < g_apBss.size(); ++ap)
    {
        const uint32_t wantMin = g_apCwMin.at(ap);
        const uint32_t wantMax = g_apCwMax.at(ap);
        uint32_t apMin = 0, apMax = 0, exact = 0, edca = 0, other = 0, missing = 0;
        for (uint32_t n = 0; n < g_apBss.at(ap).GetN(); ++n)
        {
            Config::MatchContainer match = Config::LookupMatches(beTxopPath(g_apBss.at(ap).Get(n)->GetId()));
            if (match.GetN() != 1)
            {
                ++missing;
                continue;
            }
            UintegerValue minV, maxV;
            match.Get(0)->GetAttribute("MinCw", minV);
            match.Get(0)->GetAttribute("MaxCw", maxV);
            const uint32_t gotMin = minV.Get();
            const uint32_t gotMax = maxV.Get();
            if (n == 0) // node 0 of the BSS is the AP
            {
                apMin = gotMin;
                apMax = gotMax;
                if (gotMin != wantMin || gotMax != wantMax)
                    ++other;
            }
            else if (gotMin == wantMin && gotMax == wantMax)
                ++exact;
            else if ((gotMin == wantMin || gotMin == edcaRoundedCw(wantMin)) && (gotMax == wantMax || gotMax == edcaRoundedCw(wantMax)))
                ++edca;
            else
                ++other;
        }
        NS_LOG_UNCOND("  AP" << ap + 1 << " set=" << wantMin << "/" << wantMax << " ap=" << apMin << "/" << apMax
                            << " stas: exact=" << exact << " edcaRounded(" << edcaRoundedCw(wantMin) << "/" << edcaRoundedCw(wantMax)
                            << ")=" << edca << " other=" << other << " missing=" << missing);
        if (other != 0 || missing != 0)
            ok = false;
    }
    if (!ok)
        g_apCwOk = false;
}

/*
Execute received actions
*/

bool MyExecuteActions(Ptr<OpenGymDataContainer> action)
{
    if (verbose)
        NS_LOG_UNCOND("MyExecuteActions: " << action);

    Ptr<OpenGymBoxContainer<float>> box = DynamicCast<OpenGymBoxContainer<float>>(action);
    std::vector<float> actionVector = box->GetData();

    if (type == "discrete")
    {
        CW = pow(2, 4+actionVector.at(0));
    }
    else if (type == "continuous")
    {
        CW = pow(2, actionVector.at(0) + 4);
    }
    else if (type == "direct_continuous")
    {
        CW = actionVector.at(0);
    }
    else
    {
        std::cout << "Unsupported agent type!" << endl;
        exit(0);
    }

    uint32_t min_cw = 16;
    uint32_t max_cw = 1024;

    CW = min(max_cw, max(CW, min_cw));
    outfile << current_time << "," << CW << endl;

    uint32_t cwmin = CW;
    uint32_t cwmax = CW;

    if(!dry_run){
        // Gym still sends one global action until v0.6.0: apply it to every AP's BSS.
        for (uint32_t ap = 0; ap < g_apBss.size(); ++ap)
            setApCw(ap, cwmin, cwmax);
    }
    return true;
}

float MyGetReward(void)
{
    static float ticks = 0.0;
    static uint32_t last_packets = 0;
    static float last_reward = 0.0;
    ticks += envStepTime;

    float res = g_rxPktNum - last_packets;
    float reward = res * (1500 - 20 - 8 - 8) * 8.0 / 1024 / 1024 / (5 * 150 * envStepTime) * 10;  // bits/s


    last_packets = g_rxPktNum;

    if (ticks <= 2 * envStepTime)
        return 0.0;

    if (verbose)
        NS_LOG_UNCOND("MyGetReward: " << reward);

    if(reward>1.0f || reward<0.0f)
        reward = last_reward;
    last_reward = reward;
    return last_reward;
}

/*
Collect observations
*/

Ptr<OpenGymDataContainer> MyGetObservation()
{
    recordHistory();

    std::vector<uint32_t> shape = {
        history_length,
    };
    Ptr<OpenGymBoxContainer<float>> box = CreateObject<OpenGymBoxContainer<float>>(shape);

    for (uint32_t i = 0; i < history.size(); i++)
    {
        if (history[i] >= -100 && history[i] <= 100)
            box->AddValue(history[i]);
        else
            box->AddValue(0);
    }
    for (uint32_t i = history.size(); i < history_length; i++)
    {
        box->AddValue(0);
    }
    if (verbose)
        NS_LOG_UNCOND("MyGetObservation: " << box);
    return box;
}

bool MyGetGameOver(void)
{

    return false;
}

void ScheduleNextStateRead(double envStepTime, Ptr<OpenGymInterface> openGymInterface)
{
    Simulator::Schedule(Seconds(envStepTime), &ScheduleNextStateRead, envStepTime, openGymInterface);
    openGymInterface->NotifyCurrentState();
}

void recordHistory()
{

    static uint32_t last_rx = 0;            // Previously received packets
    static uint32_t last_tx = 0;            // Previously transmitted packets
    static uint32_t calls = 0;              // Number of calls to this function
    calls++;
    current_time += envStepTime;

    float received = g_rxPktNum - last_rx;  // Received packets since the last observation
    float sent = g_txPktNum - last_tx;      // Sent (...)
    float errs = sent - received;           // Errors (...)
    float ratio;

    ratio = errs / sent;
    history.push_front(ratio);

    // Remove the oldest observation if we have filled the history
    if (history.size() > history_length)
    {
        history.pop_back();
    }

    // Replace the last observation with the current one
    last_rx = g_rxPktNum;
    last_tx = g_txPktNum;

    if (calls < history_length && non_zero_start)
    {
        // Schedule the next observation if we are not at the end of the simulation
        Simulator::Schedule(Seconds(envStepTime), &recordHistory);
    }
    else if (calls == history_length && non_zero_start)
    {
        g_rxPktNum = 0;
        g_txPktNum = 0;
        resetApCounters();
        last_rx = 0;
        last_tx = 0;
    }
}

void packetReceived(Ptr<const Packet> packet)
{
    NS_LOG_DEBUG("Client received a packet of " << packet->GetSize() << " bytes");
    g_rxPktNum++;
}

void packetSent(Ptr<const Packet> packet)
{
    g_txPktNum++;
}

void packetReceivedAp(uint32_t apIndex, Ptr<const Packet> packet)
{
    g_apRxPkt[apIndex]++;
}

void packetSentPhyAp(uint32_t apIndex, Ptr<const Packet> packet)
{
    g_apPhyTxPkt[apIndex]++;
}

void packetSentAppAp(uint32_t apIndex, Ptr<const Packet> packet)
{
    g_apAppTxPkt[apIndex]++;
}

// Hook the per-AP counters. Sinks live on the AP node, OnOff sources on its STAs, and every
// wifi device belongs to exactly one BSS, so each trace source maps to exactly one AP index.
void connectPerApStats(NodeContainer wifiApNode, std::vector<NodeContainer> apStaNodes)
{
    g_apRxPkt.assign(wifiApNode.GetN(), 0);
    g_apPhyTxPkt.assign(wifiApNode.GetN(), 0);
    g_apAppTxPkt.assign(wifiApNode.GetN(), 0);

    for (uint32_t apIndex = 0; apIndex < wifiApNode.GetN(); ++apIndex)
    {
        Ptr<Node> apNode = wifiApNode.Get(apIndex);
        for (uint32_t appIndex = 0; appIndex < apNode->GetNApplications(); ++appIndex)
        {
            Ptr<UdpServer> server = DynamicCast<UdpServer>(apNode->GetApplication(appIndex));
            if (server)
                server->TraceConnectWithoutContext("Rx", MakeBoundCallback(&packetReceivedAp, apIndex));
        }

        NodeContainer bss(apNode);
        bss.Add(apStaNodes.at(apIndex));
        for (uint32_t n = 0; n < bss.GetN(); ++n)
        {
            Ptr<Node> node = bss.Get(n);
            for (uint32_t d = 0; d < node->GetNDevices(); ++d)
            {
                Ptr<WifiNetDevice> dev = DynamicCast<WifiNetDevice>(node->GetDevice(d));
                if (dev)
                    dev->GetPhy()->TraceConnectWithoutContext("PhyTxBegin", MakeBoundCallback(&packetSentPhyAp, apIndex));
            }
            if (n == 0)
                continue; // AP node: no OnOff sources
            for (uint32_t appIndex = 0; appIndex < node->GetNApplications(); ++appIndex)
            {
                Ptr<OnOffApplication> source = DynamicCast<OnOffApplication>(node->GetApplication(appIndex));
                if (source)
                    source->TraceConnectWithoutContext("Tx", MakeBoundCallback(&packetSentAppAp, apIndex));
            }
        }
    }
}

double jainFromValues(const std::vector<double> &values)
{
    double sum = 0.0, sumSq = 0.0;
    for (double v : values)
    {
        sum += v;
        sumSq += v * v;
    }
    return sumSq > 0.0 ? sum * sum / (values.size() * sumSq) : 0.0;
}

// v0.4.0 report: per-AP sent/received/loss/throughput, network totals and consistency checks.
bool reportPerApStats(NodeContainer wifiApNode, std::vector<uint32_t> apStaCounts, double elapsed)
{
    const double payloadBits = (1500 - 20 - 8 - 8) * 8.0;
    bool ok = true;
    uint64_t sumRx = 0, sumPhyTx = 0, sumAppTx = 0;
    double sumThr = 0.0;
    std::vector<double> apThr;

    NS_LOG_UNCOND("Per-AP statistics (v0.4.0), elapsed=" << elapsed << " s:");
    for (uint32_t apIndex = 0; apIndex < wifiApNode.GetN(); ++apIndex)
    {
        uint64_t rx = g_apRxPkt[apIndex], phyTx = g_apPhyTxPkt[apIndex], appTx = g_apAppTxPkt[apIndex];
        double thr = rx * payloadBits / elapsed / 1e6;
        double lossPhy = phyTx ? (double(phyTx) - rx) / phyTx : 0.0;
        double lossApp = appTx ? (double(appTx) - rx) / appTx : 0.0;

        uint64_t sinkRx = 0;
        std::vector<double> flowRx;
        for (uint32_t appIndex = 0; appIndex < wifiApNode.Get(apIndex)->GetNApplications(); ++appIndex)
        {
            Ptr<UdpServer> server = DynamicCast<UdpServer>(wifiApNode.Get(apIndex)->GetApplication(appIndex));
            if (server)
            {
                sinkRx += server->GetReceived();
                flowRx.push_back(server->GetReceived());
            }
        }
        bool sinkOk = g_apCountersReset || sinkRx == rx;
        bool apOk = sinkOk && rx <= appTx;
        ok = ok && apOk;

        NS_LOG_UNCOND("AP" << apIndex + 1 << " stas=" << apStaCounts.at(apIndex) << " sent_phy=" << phyTx << " sent_app=" << appTx
                           << " received=" << rx << " loss_phy=" << lossPhy << " loss_app=" << lossApp
                           << " throughput=" << thr << " Mbps jain_flows=" << jainFromValues(flowRx)
                           << " sinkMatch=" << (sinkOk ? "yes" : "NO"));
        sumRx += rx;
        sumPhyTx += phyTx;
        sumAppTx += appTx;
        sumThr += thr;
        apThr.push_back(thr);
    }
    double totalThr = g_rxPktNum * payloadBits / elapsed / 1e6;
    bool totalsOk = sumRx == g_rxPktNum && sumPhyTx == g_txPktNum;
    ok = ok && totalsOk;
    NS_LOG_UNCOND("Total sent_phy=" << g_txPktNum << " (sum of APs " << sumPhyTx << ") sent_app=" << sumAppTx
                                    << " received=" << g_rxPktNum << " (sum of APs " << sumRx << ")"
                                    << " aggregate_throughput=" << totalThr << " Mbps (sum of APs " << sumThr << ")"
                                    << " jain_aps=" << jainFromValues(apThr));
    NS_LOG_UNCOND("Per-AP statistics check: " << (ok ? "PASS" : "FAIL"));
    return ok;
}

std::vector<uint32_t> parseApStaCounts(std::string apStaCounts, int nWifi)
{
    std::vector<uint32_t> counts;
    std::stringstream ss(apStaCounts);
    std::string token;

    while (std::getline(ss, token, ','))
    {
        if (token.empty())
        {
            std::cout << "Invalid --apStaCounts: empty AP station count." << endl;
            exit(1);
        }

        int count = std::stoi(token);
        if (count <= 0)
        {
            std::cout << "Invalid --apStaCounts: station counts must be positive." << endl;
            exit(1);
        }
        counts.push_back(static_cast<uint32_t>(count));
    }

    if (counts.empty())
    {
        counts.push_back(static_cast<uint32_t>(nWifi));
    }

    return counts;
}

// --apCws: exactly one CW per AP, clamped to the same 16..1024 range MyExecuteActions uses.
std::vector<uint32_t> parseApCws(std::string apCws, size_t apCount)
{
    std::vector<uint32_t> cws;
    std::stringstream ss(apCws);
    std::string token;

    while (std::getline(ss, token, ','))
    {
        if (token.empty())
        {
            std::cout << "Invalid --apCws: empty CW value." << endl;
            exit(1);
        }
        int cw = std::stoi(token);
        if (cw <= 0)
        {
            std::cout << "Invalid --apCws: CW values must be positive." << endl;
            exit(1);
        }
        cws.push_back(std::min<uint32_t>(1024, std::max<uint32_t>(16, static_cast<uint32_t>(cw))));
    }

    if (!cws.empty() && cws.size() != apCount)
    {
        std::cout << "Invalid --apCws: got " << cws.size() << " values for " << apCount << " APs." << endl;
        exit(1);
    }
    return cws;
}

void logTopology(NodeContainer wifiStaNode, NodeContainer wifiApNode, std::vector<NodeContainer> apStaNodes)
{
    NS_LOG_UNCOND("Multi-AP topology:");
    NS_LOG_UNCOND("--apCount: " << wifiApNode.GetN());
    NS_LOG_UNCOND("--totalStaCount: " << wifiStaNode.GetN());

    for (uint32_t apIndex = 0; apIndex < wifiApNode.GetN(); ++apIndex)
    {
        NS_LOG_UNCOND("AP" << apIndex + 1 << " nodeId=" << wifiApNode.Get(apIndex)->GetId()
                           << " staCount=" << apStaNodes.at(apIndex).GetN());
        for (uint32_t staIndex = 0; staIndex < apStaNodes.at(apIndex).GetN(); ++staIndex)
        {
            NS_LOG_UNCOND("AP" << apIndex + 1 << " STA" << staIndex + 1
                               << " nodeId=" << apStaNodes.at(apIndex).Get(staIndex)->GetId());
        }
    }
}

void set_phy(std::vector<uint32_t> apStaCounts, int guardInterval, NodeContainer &wifiStaNode, NodeContainer &wifiApNode, YansWifiPhyHelper &phy)
{
    Ptr<MatrixPropagationLossModel> lossModel = CreateObject<MatrixPropagationLossModel>();
    lossModel->SetDefaultLoss(50);

    uint32_t totalStaCount = 0;
    for (uint32_t count : apStaCounts)
    {
        totalStaCount += count;
    }

    wifiStaNode.Create(totalStaCount);
    wifiApNode.Create(apStaCounts.size());

    YansWifiChannelHelper channel = YansWifiChannelHelper::Default();
    Ptr<YansWifiChannel> chan = channel.Create();
    chan->SetPropagationLossModel(lossModel);
    chan->SetPropagationDelayModel(CreateObject<ConstantSpeedPropagationDelayModel>());

    phy = YansWifiPhyHelper::Default();
    phy.SetChannel(chan);

    // Set guard interval
    phy.Set("GuardInterval", TimeValue(NanoSeconds(guardInterval)));
}

void set_nodes(int channelWidth,
               int rng,
               int32_t simSeed,
               std::vector<uint32_t> apStaCounts,
               NodeContainer wifiStaNode,
               NodeContainer wifiApNode,
               YansWifiPhyHelper phy,
               WifiMacHelper mac,
               WifiHelper wifi,
               NetDeviceContainer &apDevice,
               std::vector<NodeContainer> &apStaNodes)
{
    NetDeviceContainer staDevice;
    uint32_t staOffset = 0;
    apStaNodes.clear();

    for (uint32_t apIndex = 0; apIndex < apStaCounts.size(); ++apIndex)
    {
        NodeContainer staGroup;
        for (uint32_t staIndex = 0; staIndex < apStaCounts.at(apIndex); ++staIndex)
        {
            staGroup.Add(wifiStaNode.Get(staOffset++));
        }
        apStaNodes.push_back(staGroup);

        Ssid ssid = Ssid("oscar-ap-" + std::to_string(apIndex + 1));
        mac.SetType("ns3::StaWifiMac",
                    "Ssid", SsidValue(ssid),
                    "ActiveProbing", BooleanValue(false),
                    "BE_MaxAmpduSize", UintegerValue(0));
        staDevice.Add(wifi.Install(phy, mac, staGroup));

        NodeContainer apGroup;
        apGroup.Add(wifiApNode.Get(apIndex));
        mac.SetType("ns3::ApWifiMac",
                    // Identical beacon times make multiple APs collide on every beacon; jitter only when >1 AP
                    // so the single-AP baseline stays unchanged.
                    "EnableBeaconJitter", BooleanValue(apStaCounts.size() > 1),
                    "Ssid", SsidValue(ssid));
        apDevice.Add(wifi.Install(phy, mac, apGroup));
    }

    // Set channel width
    Config::Set("/NodeList/*/DeviceList/*/$ns3::WifiNetDevice/Phy/ChannelWidth", UintegerValue(channelWidth));

    // mobility.
    MobilityHelper mobility;
    Ptr<ListPositionAllocator> positionAlloc = CreateObject<ListPositionAllocator>();

    for (uint32_t apIndex = 0; apIndex < apStaCounts.size(); ++apIndex)
    {
        positionAlloc->Add(Vector(apIndex * 50.0, 0.0, 0.0));
    }
    for (uint32_t apIndex = 0; apIndex < apStaCounts.size(); ++apIndex)
    {
        double baseX = apIndex * 50.0;
        for (uint32_t staIndex = 0; staIndex < apStaCounts.at(apIndex); ++staIndex)
        {
            double x = baseX + (static_cast<int>(staIndex % 10) - 4.5);
            double y = 3.0 + static_cast<int>(staIndex / 10) * 2.0;
            positionAlloc->Add(Vector(x, y, 0.0));
        }
    }
    mobility.SetPositionAllocator(positionAlloc);

    mobility.SetMobilityModel("ns3::ConstantPositionMobilityModel");

    mobility.Install(wifiApNode);
    mobility.Install(wifiStaNode);
    /* Internet stack*/
    InternetStackHelper stack;
    stack.Install(wifiApNode);
    stack.Install(wifiStaNode);

    //Random
    if(simSeed!=-1)
        RngSeedManager::SetSeed(simSeed);
    RngSeedManager::SetRun(rng);

    Ipv4AddressHelper address;
    address.SetBase("192.168.1.0", "255.255.255.0");
    Ipv4InterfaceContainer staNodeInterface;
    Ipv4InterfaceContainer apNodeInterface;

    staNodeInterface = address.Assign(staDevice);
    apNodeInterface = address.Assign(apDevice);

    logTopology(wifiStaNode, wifiApNode, apStaNodes);

    // v0.5.0: one BSS (AP + its STAs) per AP index, each with its own CW.
    g_apBss.clear();
    for (uint32_t apIndex = 0; apIndex < apStaCounts.size(); ++apIndex)
    {
        NodeContainer bss(wifiApNode.Get(apIndex)); // AP first: checkApCw relies on it
        bss.Add(apStaNodes.at(apIndex));
        g_apBss.push_back(bss);
    }
    g_apCwMin.assign(g_apBss.size(), 0);
    g_apCwMax.assign(g_apBss.size(), 0);

    if (dry_run)
        NS_LOG_UNCOND("Default CW");
    for (uint32_t apIndex = 0; apIndex < g_apBss.size(); ++apIndex)
    {
        if (dry_run)
            setApCw(apIndex, 16, 1024);
        else if (!g_apCwOverride.empty())
            setApCw(apIndex, g_apCwOverride.at(apIndex), g_apCwOverride.at(apIndex));
        else
            setApCw(apIndex, CW, CW);
    }
}

void set_sim(bool tracing, bool dry_run, bool disableGym, int warmup, uint32_t openGymPort, YansWifiPhyHelper phy, NetDeviceContainer apDevice, int end_delay, Ptr<FlowMonitor> &monitor, FlowMonitorHelper &flowmon)
{
    monitor = flowmon.InstallAll();
    monitor->SetAttribute("StartTime", TimeValue(Seconds(warmup)));

    if (tracing)
    {
        phy.SetPcapDataLinkType(WifiPhyHelper::DLT_IEEE802_11_RADIO);
        for (uint32_t apIndex = 0; apIndex < apDevice.GetN(); ++apIndex)
        {
            phy.EnablePcap("cw-ap" + std::to_string(apIndex + 1), apDevice.Get(apIndex));
        }
    }

    if (!disableGym)
    {
        Ptr<OpenGymInterface> openGymInterface = CreateObject<OpenGymInterface>(openGymPort);
        openGymInterface->SetGetActionSpaceCb(MakeCallback(&MyGetActionSpace));
        openGymInterface->SetGetObservationSpaceCb(MakeCallback(&MyGetObservationSpace));
        openGymInterface->SetGetGameOverCb(MakeCallback(&MyGetGameOver));
        openGymInterface->SetGetObservationCb(MakeCallback(&MyGetObservation));
        openGymInterface->SetGetRewardCb(MakeCallback(&MyGetReward));
        openGymInterface->SetGetExtraInfoCb(MakeCallback(&MyGetExtraInfo));
        openGymInterface->SetExecuteActionsCb(MakeCallback(&MyExecuteActions));

        if (non_zero_start)
        {
            Simulator::Schedule(Seconds(1.0), &recordHistory);
            Simulator::Schedule(Seconds(envStepTime * history_length + 1.0), &ScheduleNextStateRead, envStepTime, openGymInterface);
        }
        else
        {
            Simulator::Schedule(Seconds(1.0), &ScheduleNextStateRead, envStepTime, openGymInterface);
        }
    }
    else
    {
        NS_LOG_UNCOND("OpenGym disabled");
    }


    Simulator::Stop(Seconds(simulationTime + end_delay + 1.0 + envStepTime*(history_length+1)));

    NS_LOG_UNCOND("Simulation started");
    Simulator::Run();
}

// STA node id -> BSSID of the AP it last associated with, and per-STA DeAssoc counts.
std::map<uint32_t, Mac48Address> g_staBssid;
std::map<uint32_t, uint32_t> g_staDeAssocCount;

uint32_t nodeIdFromContext(std::string context)
{
    const std::string key = "/NodeList/";
    size_t start = context.find(key);
    if (start == std::string::npos)
    {
        std::cout << "Unexpected trace context: " << context << endl;
        exit(1);
    }
    return static_cast<uint32_t>(std::stoul(context.substr(start + key.size())));
}

void staAssociated(std::string context, Mac48Address bssid)
{
    g_staBssid[nodeIdFromContext(context)] = bssid;
}

void staDeAssociated(std::string context, Mac48Address bssid)
{
    g_staDeAssocCount[nodeIdFromContext(context)]++;
}

// Log-only v0.3.0 checks: every STA associated with exactly its own AP.
bool reportAssociation(std::vector<NodeContainer> apStaNodes, NetDeviceContainer apDevice)
{
    bool ok = true;
    for (uint32_t apIndex = 0; apIndex < apStaNodes.size(); ++apIndex)
    {
        Mac48Address apBssid = Mac48Address::ConvertFrom(apDevice.Get(apIndex)->GetAddress());
        uint32_t associated = 0, mismatched = 0, unassociated = 0, deassoc = 0;
        for (uint32_t staIndex = 0; staIndex < apStaNodes.at(apIndex).GetN(); ++staIndex)
        {
            uint32_t nodeId = apStaNodes.at(apIndex).Get(staIndex)->GetId();
            std::map<uint32_t, Mac48Address>::const_iterator it = g_staBssid.find(nodeId);
            if (it == g_staBssid.end())
                ++unassociated;
            else if (it->second == apBssid)
                ++associated;
            else
                ++mismatched;
            if (g_staDeAssocCount.count(nodeId))
                deassoc += g_staDeAssocCount[nodeId];
        }
        NS_LOG_UNCOND("AP" << apIndex + 1 << " association: ok=" << associated << "/" << apStaNodes.at(apIndex).GetN()
                           << " wrongAp=" << mismatched << " unassociated=" << unassociated << " deassoc=" << deassoc);
        ok = ok && mismatched == 0 && unassociated == 0;
    }
    return ok;
}

void signalHandler(int signum)
{
    cout << "Interrupt signal " << signum << " received.\n";
    exit(signum);
}

int main(int argc, char *argv[])
{
    int nWifi = 5;
    bool tracing = false;
    bool useRts = false;
    int mcs = 11;
    int channelWidth = 20;
    int guardInterval = 800;
    string offeredLoad = "150";
    int port = 1025;
    string outputCsv = "cw.csv";
    string scenario = "basic";
    string apStaCountsArg = "";
    string apCwsArg = "";
    dry_run = false;

    int rng = 1;
    int warmup = 1;

    uint32_t openGymPort = 5555;
    int32_t simSeed = -1;

    signal(SIGTERM, signalHandler);
    outfile << "SimulationTime,CW" << endl;

    CommandLine cmd;
    cmd.AddValue("openGymPort", "Specify port number. Default: 5555", openGymPort);
    cmd.AddValue("CW", "Value of Contention Window", CW);
    cmd.AddValue("historyLength", "Length of history window", history_length);
    cmd.AddValue("nWifi", "Number of wifi 802.11ax STA devices", nWifi);
    cmd.AddValue("verbose", "Tell echo applications to log if true", verbose);
    cmd.AddValue("tracing", "Enable pcap tracing", tracing);
    cmd.AddValue("rng", "Number of RngRun", rng);
    cmd.AddValue("simTime", "Simulation time in seconds. Default: 10s", simulationTime);
    cmd.AddValue("envStepTime", "Step time in seconds. Default: 0.1s", envStepTime);
    cmd.AddValue("agentType", "Type of agent actions: discrete, continuous", type);
    cmd.AddValue("nonZeroStart", "Start only after history buffer is filled", non_zero_start);
    cmd.AddValue("scenario", "Scenario for analysis: basic, convergence, reaction", scenario);
    cmd.AddValue("dryRun", "Execute scenario with BEB and no agent interaction", dry_run);
    cmd.AddValue("disableGym", "Run ns-3 without OpenGym/ZMQ interaction", disable_gym);
    cmd.AddValue("apStaCounts", "Comma-separated station counts per AP, e.g. 20,40. Default: empty = single AP with nWifi stations", apStaCountsArg);
    cmd.AddValue("apCws", "Comma-separated fixed CW per AP, e.g. 32,256 (one per AP, clamped 16..1024). Ignored when dryRun=true. Default: empty = every AP uses CW", apCwsArg);
    cmd.AddValue("seed", "Random seed", simSeed);

    cmd.Parse(argc, argv);

    std::vector<uint32_t> apStaCounts = parseApStaCounts(apStaCountsArg, nWifi);
    g_apCwOverride = parseApCws(apCwsArg, apStaCounts.size());
    nWifi = 0;
    for (uint32_t count : apStaCounts)
    {
        nWifi += count;
    }

    NS_LOG_UNCOND("Ns3Env parameters:");
    NS_LOG_UNCOND("--nWifi: " << nWifi);
    NS_LOG_UNCOND("--apStaCounts: " << (apStaCountsArg.empty() ? "(single AP, nWifi stations)" : apStaCountsArg));
    NS_LOG_UNCOND("--apCws: " << (apCwsArg.empty() ? "(none, every AP uses CW)" : apCwsArg) << (dry_run && !apCwsArg.empty() ? " (ignored: dryRun)" : ""));
    NS_LOG_UNCOND("--simulationTime: " << simulationTime);
    NS_LOG_UNCOND("--openGymPort: " << openGymPort);
    NS_LOG_UNCOND("--envStepTime: " << envStepTime);
    NS_LOG_UNCOND("--seed: " << simSeed);
    NS_LOG_UNCOND("--agentType: " << type);
    NS_LOG_UNCOND("--scenario: " << scenario);
    NS_LOG_UNCOND("--dryRun: " << dry_run);
    NS_LOG_UNCOND("--disableGym: " << disable_gym);

    if (verbose)
    {
        LogComponentEnable("UdpEchoClientApplication", LOG_LEVEL_INFO);
        LogComponentEnable("UdpEchoServerApplication", LOG_LEVEL_INFO);
    }

    if (useRts)
    {
        Config::SetDefault("ns3::WifiRemoteStationManager::RtsCtsThreshold", StringValue("0"));
    }

    NodeContainer wifiStaNode;
    NodeContainer wifiApNode;
    YansWifiPhyHelper phy;
    set_phy(apStaCounts, guardInterval, wifiStaNode, wifiApNode, phy);

    WifiMacHelper mac;
    WifiHelper wifi;

    wifi.SetStandard(WIFI_PHY_STANDARD_80211ax_5GHZ);

    std::ostringstream oss;
    oss << "HeMcs" << mcs;
    wifi.SetRemoteStationManager("ns3::ConstantRateWifiManager", "DataMode", StringValue(oss.str()),
                                 "ControlMode", StringValue(oss.str()));


    NetDeviceContainer apDevice;
    std::vector<NodeContainer> apStaNodes;
    set_nodes(channelWidth, rng, simSeed, apStaCounts, wifiStaNode, wifiApNode, phy, mac, wifi, apDevice, apStaNodes);

    Config::Connect("/NodeList/*/DeviceList/*/$ns3::WifiNetDevice/Mac/$ns3::StaWifiMac/Assoc", MakeCallback(&staAssociated));
    Config::Connect("/NodeList/*/DeviceList/*/$ns3::WifiNetDevice/Mac/$ns3::StaWifiMac/DeAssoc", MakeCallback(&staDeAssociated));

    ScenarioFactory helper = ScenarioFactory(nWifi, wifiStaNode, wifiApNode, apStaNodes, port, offeredLoad, history_length);
    wifiScenario = helper.getScenario(scenario);


    if (non_zero_start)
        end_delay = envStepTime * history_length + 1.0;
    else
        end_delay = 0.0;


    wifiScenario->installScenario(simulationTime + end_delay + envStepTime, envStepTime, MakeCallback(&packetReceived));

    Config::ConnectWithoutContext("/NodeList/*/DeviceList/*/$ns3::WifiNetDevice/Phy/PhyTxBegin", MakeCallback(&packetSent));
    connectPerApStats(wifiApNode, apStaNodes);

    wifiScenario->PopulateARPcache();
    Ipv4GlobalRoutingHelper::PopulateRoutingTables();


    Simulator::Schedule(Seconds(0), &checkApCw, std::string("start"));
    Simulator::Schedule(Seconds(warmup), &checkApCw, std::string("warmup"));

    set_sim(tracing, dry_run, disable_gym, warmup, openGymPort, phy, apDevice, end_delay, monitor, flowmon);

    double flowThr;
    float res =  g_rxPktNum * (1500 - 20 - 8 - 8) * 8.0 / 1024 / 1024;
    printf("Sent mbytes: %.2f\tThroughput: %.3f", res, res/simulationTime);
    ofstream myfile;
    myfile.open(outputCsv, ios::app);


    // v0.3.0 validation maps: IPv4 address -> AP index (sinks) and STA -> owning AP index.
    std::map<Ipv4Address, uint32_t> apIpToIndex;
    std::map<Ipv4Address, uint32_t> staIpToAp;
    for (uint32_t apIndex = 0; apIndex < wifiApNode.GetN(); ++apIndex)
    {
        apIpToIndex[wifiApNode.Get(apIndex)->GetObject<Ipv4>()->GetAddress(1, 0).GetLocal()] = apIndex;
        for (uint32_t staIndex = 0; staIndex < apStaNodes.at(apIndex).GetN(); ++staIndex)
        {
            staIpToAp[apStaNodes.at(apIndex).Get(staIndex)->GetObject<Ipv4>()->GetAddress(1, 0).GetLocal()] = apIndex;
        }
    }
    std::vector<uint32_t> apFlowCount(wifiApNode.GetN(), 0);
    std::vector<uint64_t> apRxPackets(wifiApNode.GetN(), 0);
    std::vector<double> apThroughput(wifiApNode.GetN(), 0.0);
    uint32_t crossApFlows = 0;

    Ptr<Ipv4FlowClassifier> classifier = DynamicCast<Ipv4FlowClassifier>(flowmon.GetClassifier());
    std::map<FlowId, FlowMonitor::FlowStats> stats = monitor->GetFlowStats();
    for (std::map<FlowId, FlowMonitor::FlowStats>::const_iterator i = stats.begin(); i != stats.end(); ++i)
    {
        auto time = std::time(nullptr);
        auto tm = *std::localtime(&time);
        Ipv4FlowClassifier::FiveTuple t = classifier->FindFlow(i->first);
        flowThr = i->second.rxBytes * 8.0 / simulationTime / 1000 / 1000;
        NS_LOG_UNCOND("Flow " << i->first << " (" << t.sourceAddress << " -> " << t.destinationAddress << ")\tThroughput: " << flowThr << " Mbps\tTime: " << i->second.timeLastRxPacket.GetSeconds() - i->second.timeFirstTxPacket.GetSeconds() << " s\tRx packets " << i->second.rxPackets);
        myfile << std::put_time(&tm, "%Y-%m-%d %H:%M") << "," << CW << "," << nWifi << "," << RngSeedManager::GetRun() << "," << t.sourceAddress << "," << t.destinationAddress << "," << flowThr;
        myfile << std::endl;

        std::map<Ipv4Address, uint32_t>::const_iterator dstAp = apIpToIndex.find(t.destinationAddress);
        std::map<Ipv4Address, uint32_t>::const_iterator srcAp = staIpToAp.find(t.sourceAddress);
        if (dstAp == apIpToIndex.end() || srcAp == staIpToAp.end() || dstAp->second != srcAp->second)
        {
            ++crossApFlows;
            continue;
        }
        apFlowCount[dstAp->second]++;
        apRxPackets[dstAp->second] += i->second.rxPackets;
        apThroughput[dstAp->second] += flowThr;
    }
    myfile.close();

    NS_LOG_UNCOND("Per-AP sink check (flow-monitor, v0.3.0 validation only):");
    for (uint32_t apIndex = 0; apIndex < wifiApNode.GetN(); ++apIndex)
    {
        // UdpServer counts every packet its sink received over the whole run (FlowMonitor only counts after warmup).
        uint64_t sinkReceived = 0;
        for (uint32_t appIndex = 0; appIndex < wifiApNode.Get(apIndex)->GetNApplications(); ++appIndex)
        {
            Ptr<UdpServer> server = DynamicCast<UdpServer>(wifiApNode.Get(apIndex)->GetApplication(appIndex));
            if (server)
                sinkReceived += server->GetReceived();
        }
        NS_LOG_UNCOND("AP" << apIndex + 1 << " sinks=" << apStaCounts.at(apIndex) << " sinkReceivedPackets=" << sinkReceived
                           << " | flowmon flows=" << apFlowCount[apIndex] << " rxPackets=" << apRxPackets[apIndex]
                           << " throughput=" << apThroughput[apIndex] << " Mbps");
    }
    NS_LOG_UNCOND("Flows not terminating at their own AP: " << crossApFlows);
    bool associationOk = reportAssociation(apStaNodes, apDevice);
    NS_LOG_UNCOND("Association check: " << (associationOk ? "PASS" : "FAIL"));
    reportPerApStats(wifiApNode, apStaCounts, Simulator::Now().GetSeconds());
    checkApCw("end");
    NS_LOG_UNCOND("Per-AP CW check: " << (g_apCwOk ? "PASS" : "FAIL"));

    Simulator::Destroy();
    NS_LOG_UNCOND("Packets registered by handler: " << g_rxPktNum << " Packets" << endl);

    return 0;
}
